
-- colo bluez
-- colo bocau
-- colo jellybeans
-- colo candycode
-- colo janah
-- colo wal
-- colo vividchalk
-- colo gruvbox
-- colo xoria256
-- colo wombat256
-- colo inkpot
-- colo dracula
-- TEMPUS COLOR SCHEMES
-- ==============================
-- colo tempus_warp
-- colo tempus_autumn
-- ==============================
-- colo desert
-- colo ir_black
-- colo molokai
-- colo murphy
-- colo slate
-- colo blackboard
-- colo blazer
-- colo cobalt2
-- colo gardener
-- colo dante
-- From https://github.com/tomasr/molokai
-- vim.cmd('colorscheme molokai')
-- For the dark molokai theme
-- vim.g.rehash256 = 1
vim.g.tokyonight_style = "night"
vim.cmd('colorscheme tokyonight')
-- colo distinguished
-- colo colorful256
-- vim.g.modus_moody_enable = 1
-- vim.cmd('colorscheme modus-vivendi')
