#+TITLE: Emacs config
#+AUTHOR: Anthony
#+LANGUAGE: en
#+OPTIONS: num:nil

* Quality of life
** Enable line numbers
Emacs breaks certain modes when it has line-numbers-mode enabled, (like docview or ansi-term) so I utilize the approach of only enabling it on some major modes rather than globally
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (add-hook 'text-mode-hook 'display-line-numbers-mode)
#+END_SRC
** Show parent parentheses
#+BEGIN_SRC emacs-lisp
  (show-paren-mode 1)
#+END_SRC
** Disable the default startup screen
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)
#+END_SRC
** Disable most gui elements
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+END_SRC
** Enable copypasting outside of Emacs
#+BEGIN_SRC emacs-lisp
  (setq select-enable-clipboard t)
#+END_SRC
** Disable automatic creation of backup files
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+END_SRC
** Enable conservative scrolling
#+BEGIN_SRC emacs-lisp
  (setq scroll-conservatively 100)
#+END_SRC
** Disable ring-bell
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC
** Indentation
#+BEGIN_SRC emacs-lisp
  (setq-default tab-width 4)
  (setq-default standard-indent 4)
  (setq c-basic-offset tab-width)
  (setq-default electric-indent-inhibit t)
  ;; Use spaces instead of tabs
  (setq-default indent-tabs-mode nil)
  (setq backward-delete-char-untabify-method 'nil)
#+END_SRC
** Enable prettify symbols mode
#+BEGIN_SRC emacs-lisp
       (setq prettify-symbols-alist '(("TODO" . "")
                    ("WAIT" . "")
                    ("NOPE" . "")
                    ("DONE" . "")
                    ("[#A]" . "")
                    ("[#B]" . "")
                    ("[#C]" . "")
                    ("[ ]" . "")
                    ("[X]" . "")
                    ("[-]" . "")
                    ("#+BEGIN_SRC" . "")
                    ("#+END_SRC" . "―")
                    (":PROPERTIES:" . "")
                    (":END:" . "―")
                    ("#+STARTUP:" . "")
                    ("#+TITLE: " . "")
                    ("#+RESULTS:" . "")
                    ("#+NAME:" . "")
                    ("#+ROAM_TAGS:" . "")
                    ("#+FILETAGS:" . "")
                    ("#+HTML_HEAD:" . "")
                    ("#+SUBTITLE:" . "")
                    ("#+AUTHOR:" . "")
                    (":Effort:" . "")
                    ("SCHEDULED:" . "")
                    ("DEADLINE:" . "")))
    (global-prettify-symbols-mode t)
#+END_SRC
** Enable bracket pair-matching
#+BEGIN_SRC emacs-lisp
  (setq electric-pair-pairs '(
                              (?\{ . ?\})
                              (?\( . ?\))
                              (?\[ . ?\])
                              (?\" . ?\")
                              ))
  (electric-pair-mode t)
#+END_SRC
** Creating a new window switches your cursor to it
#+BEGIN_SRC emacs-lisp
  (defun split-and-follow-horizontally ()
    (interactive)
    (split-window-below)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

  (defun split-and-follow-vertically ()
    (interactive)
    (split-window-right)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+END_SRC
** Transform yes-or-no questions into y-or-n
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Easier resize bindigs
Super - Control - <arrow>
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "s-C-<left>") 'shrink-window-horizontally)
  (global-set-key (kbd "s-C-<right>") 'enlarge-window-horizontally)
  (global-set-key (kbd "s-C-<down>") 'shrink-window)
  (global-set-key (kbd "s-C-<up>") 'enlarge-window)
#+END_SRC
** Highlight current line
#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode t)
#+END_SRC
** Changing the font
#+Begin_SRC emacs-lisp
  (if (member "Fira Code"
  (font-family-list))(add-to-list 'default-frame-alist
  '(font . "Fira Code-12")))
#+END_SRC
** Enable deleting selection by typing
#+BEGIN_SRC emacs-lisp
(delete-selection-mode)
#+END_SRC

* Custom functions and key mappings
** C/C++
*** Insert header guards
#+BEGIN_SRC emacs-lisp
    (defun maybe-add-newline-at-buf-start ()
      (if (and (char-equal (char-after (point-min)) ?\n)
               (char-equal (char-after (1+ (point-min))) ?\n))
          ""
        "\n"))
    (defun maybe-add-newline-at-buf-end ()
      (if (and (char-equal (char-before (point-max)) ?\n)
               (char-equal (char-before (1- (point-max))) ?\n))
          ""
        "\n"))

      (defun add_header_guards ()
      "Add header guards to .h files"
      (interactive)
      (if (buffer-file-name)
          (let*
              ((fName (upcase (file-name-nondirectory (file-name-sans-extension buffer-file-name))))
               (ifDef (concat "#ifndef " fName "_H" "\n#define " fName "_H"
                              (maybe-add-newline-at-buf-start)))
               (begin (point-marker))
               )
            (progn
              ; If less then 5 characters are in the buffer, insert the class definition
              (if (< (- (point-max) (point-min)) 5 )
                  (progn
                    (insert "\nclass " (capitalize fName) "{\npublic:\n\nprivate:\n\n};\n")
                    (goto-char (point-min))
                    (next-line-nomark 3)
                    (setq begin (point-marker))
                    )
                )

              ;Insert the Header Guard
              (goto-char (point-min))
              (insert ifDef)
              (goto-char (point-max))
              (insert (maybe-add-newline-at-buf-end) "#endif" " //" fName "_H")
              (goto-char begin))
            )
        ;else
        (message (concat "Buffer " (buffer-name) " must have a filename"))
        )
      )
  (add-hook 'c-mode-hook '(lambda ()
    (define-key c-mode-map (kbd "C-c C-x C-d")
      'add_header_guards)
  ))

  (add-hook 'c++-mode-hook '(lambda ()
    (define-key c++-mode-map (kbd "C-c C-x C-d")
      'add_header_guards)
  ))
#+END_SRC
* Org-mode
** Description
One of the main selling points of Emacs! Org Mode!
** Code
#+BEGIN_SRC emacs-lisp
        (use-package org-indent
          :straight nil
          :diminish org-indent-mode)

        (use-package htmlize
          :straight t)

      (use-package org-bullets
        :straight t
        :hook ('org-mode-hook . (lambda () org-bullets-mode))
        :hook ('org-mode-hook 'variable-pitch-mode)
        :config
        (require 'org-bullets))

    (defun echo-area-tooltips ()
      "Show tooltips in the echo area automatically for current buffer."
      (setq-local help-at-pt-display-when-idle t
                  help-at-pt-timer-delay 0)
      (help-at-pt-cancel-timer)
      (help-at-pt-set-timer))

    (add-hook 'org-mode-hook #'echo-area-tooltips)
  ;; Sets LaTeX preview size
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 2.0))

  (use-package org-beautify-theme
    :straight t)

  (add-hook 'org-mode-hook '(lambda () (load-theme 'org-beautify t)))
#+END_SRC

* Packages
** Initialize =async=
*** Description
Utilize asynchronous processes whenever possible
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package async
    :straight t
    :init
    (dired-async-mode 1))
#+END_SRC
** Initialize =powerline=
*** Description
Emacs version of the Vim powerline.
*** Code
#+BEGIN_SRC emacs-lisp
(use-package powerline
  :straight t
  :config
   (powerline-default-theme))
#+END_SRC
** Initialize =all-the-icons=
*** Description
Bring nice icons to emacs
*** Code
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons
  :straight t
  :config
    ;; (all-the-icons-install-fonts)

)
#+END_SRC
** Initialize =key-chord=
*** Description
Key-chord lets you bind commands to combinations of key-strokes.
Here a “key chord” means two keys pressed simultaneously,
or a single key quickly pressed twice. (*)
*** Code
#+BEGIN_SRC emacs-lisp
(use-package key-chord
  :straight t
  :config
    (key-chord-mode 1))
#+END_SRC
** Initialize =vertico=
*** Description
Vertico provides a performant and minimalistic vertical completion UI based on the default completion system
*** Code
#+BEGIN_SRC emacs-lisp
        (use-package vertico
          :straight t
          :custom
          (vertico-cycle t)
          :init
          (vertico-mode))
        ;; Built in
        (use-package savehist
          :straight nil
          :init
          (savehist-mode))

        (use-package marginalia
          :straight t
          :after vertico
          :custom
          (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
          :init
)
#+END_SRC
** Initialize =undo-tree=
*** Description
Emacs’s undo system allows you to recover any past state of a buffer. To do this, Emacs
treats “undo” itself as just another editing action that can be undone. This can be
confusing and difficult to use. If you make an edit while undoing multiple changes, you
“break the undo chain”. To get back to where you were, you have to undo all the undos
you just did, then undo all the changes you’d already undone before. Only then can you
continue undoing from where you left off. If this sounds confusing, it’s because it is!
Hence, a number of packages exist that replace it with the undo/redo system

Instead of treating undo/redo as a linear sequence of changes, undo-tree-mode treats
undo history as a branching tree of changes, similar to the way Vim handles it.
*** Code
#+BEGIN_SRC emacs-lisp
(use-package undo-tree
  :straight t
  :init
  (global-undo-tree-mode 1))
#+END_SRC
** Initialize =page-break-lines=
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package page-break-lines
    :straight t
    :diminish (page-break-lines-mode visual-line-mode))
#+END_SRC
** Initialize =projectile=
*** Description
Projectile is a project interaction library for Emacs.
Its goal is to provide a nice set of features
operating on a project level without introducing
external dependencies (when feasible).
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package projectile
   :straight t
   :config
     (projectile-mode +1)
    (define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
    (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map))
#+END_SRC
** Initialize =treemacs=
*** Description
Neat side-bar file and project explorer
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package treemacs
    :straight t
    :init
    (with-eval-after-load 'winum
      (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
    :config
    (progn
      (setq treemacs-collapse-dirs                 (if (executable-find "python3") 3 0)
            treemacs-deferred-git-apply-delay      0.5
            treemacs-display-in-side-window        t
            treemacs-eldoc-display                 t
            treemacs-file-event-delay              5000
            treemacs-file-follow-delay             0.2
            treemacs-follow-after-init             t
            treemacs-git-command-pipe              ""
            treemacs-goto-tag-strategy             'refetch-index
            treemacs-indentation                   2
            treemacs-indentation-string            " "
            treemacs-is-never-other-window         nil
            treemacs-max-git-entries               5000
            treemacs-missing-project-action        'ask
            treemacs-no-png-images                 nil
            treemacs-no-delete-other-windows       t
            treemacs-project-follow-cleanup        nil
            treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
            treemacs-recenter-distance             0.1
            treemacs-recenter-after-file-follow    nil
            treemacs-recenter-after-tag-follow     nil
            treemacs-recenter-after-project-jump   'always
            treemacs-recenter-after-project-expand 'on-distance
            treemacs-show-cursor                   nil
            treemacs-show-hidden-files             t
            treemacs-silent-filewatch              nil
            treemacs-silent-refresh                nil
            treemacs-sorting                       'alphabetic-desc
            treemacs-space-between-root-nodes      t
            treemacs-tag-follow-cleanup            t
            treemacs-tag-follow-delay              1.5
            treemacs-width                         30)
      (treemacs-resize-icons 11)

      (treemacs-follow-mode t)
      (treemacs-filewatch-mode t)
      (treemacs-fringe-indicator-mode t)
      (pcase (cons (not (null (executable-find "git")))
                   (not (null (executable-find "python3"))))
        (`(t . t)
         (treemacs-git-mode 'deferred))
        (`(t . _)
         (treemacs-git-mode 'simple))))
    :bind
    (:map global-map
          ("M-0"       . treemacs-select-window)
          ("C-x t 1"   . treemacs-delete-other-windows)
          ("C-x t t"   . treemacs)
          ("C-x t B"   . treemacs-bookmark)
          ("C-x t C-t" . treemacs-find-file)
          ("C-x t M-t" . treemacs-find-tag)))

    (use-package treemacs-icons-dired
      :after treemacs dired
      :straight t
      :config (treemacs-icons-dired-mode))
#+END_SRC
** Initialize =dashboard=
*** Description
The frontend of Witchmacs; without this there'd be no Marisa in your Emacs startup screen
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package dashboard
    :straight t
    :config
    (dashboard-setup-startup-hook)
        (setq dashboard-set-heading-icons t)
        (setq dashboard-set-file-icons t)
        (setq dashboard-projects-backend 'projectile)
        (setq dashboard-items '((projects . 5)
                                (recents . 5)
                                (bookmarks . 5)
                                (agenda . 5)))
    (setq dashboard-banner-logo-title "E M A C S - The worst text editor!")
    (setq dashboard-startup-banner "~/.config/emacs/emacs-logo.png")
    (setq dashboard-center-content t)
    (setq dashboard-show-shortcuts nil)
    (setq dashboard-set-init-info t)
    ;; (setq dashboard-init-info (format "%d packages loaded in %s"
    ;;                                   (length package-activated-list) (emacs-init-time)))
    (setq dashboard-set-footer t)
    (setq dashboard-set-navigator t))
#+END_SRC
*** Notes
If you pay close attention to the code in dashboard, you'll  notice that it uses custom functions defined under the :preface use-package block. I wrote all of those functions by looking at other people's Emacs distributions (Mainly [[https://github.com/seagle0128/.emacs.d][Centaur Emacs]]) and then experimenting and adapting them to Witchmacs. If you dig around, you'll find the same things I did - maybe even more!
** Initialize =swiper=
*** Description
When doing <SPC> s s to search, you get this very nice and neat mini-buffer that you can traverse with the arrow keys (or C-n and C-p) and then press <RET> to select where you want to go
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package swiper
    :straight t
    :bind ("C-s" . 'swiper)
    ("C-r" . 'swiper-backward))
#+END_SRC

** Initialize =magit=
*** Description
Git porcelain for Emacs
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :straight t)
#+END_SRC
** Initialize =format-all-the-code=
*** Description
Lets you auto-format source code in many languages
using the same command for all languages,
instead of learning a different Emacs package
and formatting command for each language.
*** Code
#+BEGIN_SRC emacs-lisp
(use-package format-all
  :straight t)
#+END_SRC
** Initializn =doom-modeline=
*** description
A fancy and fast mode-line inspired by minimalism design.
*** Cose
#+BEGIN_SRC emacs-lisp
(use-package doom-modeline
  :straight t
  :hook (after-init . doom-modeline-mode)
  :config
;; How tall the mode-line should be. It's only respected in GUI.
;; If the actual char height is larger, it respects the actual height.
(setq doom-modeline-height 35)
;; How to detect the project root.
;; The default priority of detection is `ffip' > `projectile' > `project'.
;; nil means to use `default-directory'.
;; The project management packages have some issues on detecting project root.
;; e.g. `projectile' doesn't handle symlink folders well, while `project' is unable
;; to hanle sub-projects.
;; You can specify one if you encounter the issue.
(setq doom-modeline-project-detection 'projectile)
;; Whether display icons in the mode-line.
;; While using the server mode in GUI, should set the value explicitly.
(setq doom-modeline-icon (display-graphic-p))
;; Whether display icons in the mode-line.
;; While using the server mode in GUI, should set the value explicitly.
(setq doom-modeline-icon (display-graphic-p))
;; Whether display the colorful icon for `major-mode'.
;; It respects `all-the-icons-color-icons'.
(setq doom-modeline-major-mode-color-icon t)
;; Whether display the icon for the buffer state. It respects `doom-modeline-icon'.
(setq doom-modeline-buffer-state-icon t)
;; Whether display the modification icon for the buffer.
;; It respects `doom-modeline-icon' and `doom-modeline-buffer-state-icon'.
(setq doom-modeline-buffer-modification-icon t)
;; Whether to use unicode as a fallback (instead of ASCII) when not using icons.
(setq doom-modeline-unicode-fallback t)
;; Whether display the minor modes in the mode-line.
(setq doom-modeline-minor-modes nil)
;; If non-nil, a word count will be added to the selection-info modeline segment.
(setq doom-modeline-enable-word-count t)
;; Major modes in which to display word count continuously.
;; Also applies to any derived modes. Respects `doom-modeline-enable-word-count'.
;; If it brings the sluggish issue, disable `doom-modeline-enable-word-count' or
;; remove the modes from `doom-modeline-continuous-word-count-modes'.
(setq doom-modeline-continuous-word-count-modes '(markdown-mode gfm-mode org-mode))

;; Whether display the buffer encoding.
(setq doom-modeline-buffer-encoding t)

;; Whether display the indentation information.
(setq doom-modeline-indent-info nil)

;; If non-nil, only display one number for checker information if applicable.
(setq doom-modeline-checker-simple-format t)

;; The maximum number displayed for notifications.
(setq doom-modeline-number-limit 99)

;; The maximum displayed length of the branch name of version control.
(setq doom-modeline-vcs-max-length 20)

;; Whether display the workspace name. Non-nil to display in the mode-line.
(setq doom-modeline-workspace-name t)

;; Whether display the perspective name. Non-nil to display in the mode-line.
(setq doom-modeline-persp-name t)

;; If non nil the default perspective name is displayed in the mode-line.
(setq doom-modeline-display-default-persp-name nil)

;; If non nil the perspective name is displayed alongside a folder icon.
(setq doom-modeline-persp-icon t)

;; Whether display the `lsp' state. Non-nil to display in the mode-line.
(setq doom-modeline-lsp t)

;; Whether display the GitHub notifications. It requires `ghub' package.
(setq doom-modeline-github nil)

;; The interval of checking GitHub.
(setq doom-modeline-github-interval (* 30 60))

;; Whether display the mu4e notifications. It requires `mu4e-alert' package.
(setq doom-modeline-mu4e nil)

;; Whether display the gnus notifications.
(setq doom-modeline-gnus t)

;; Wheter gnus should automatically be updated and how often (set to 0 or smaller than 0 to disable)
(setq doom-modeline-gnus-timer 2)

;; Wheter groups should be excludede when gnus automatically being updated.
(setq doom-modeline-gnus-excluded-groups '("dummy.group"))

;; Whether display the IRC notifications. It requires `circe' or `erc' package.
(setq doom-modeline-irc t)

;; Function to stylize the irc buffer names.
(setq doom-modeline-irc-stylize 'identity)

;; Whether display the environment version.
(setq doom-modeline-env-version t)
;; Or for individual languages
(setq doom-modeline-env-enable-python t)
(setq doom-modeline-env-enable-ruby t)
(setq doom-modeline-env-enable-perl t)
(setq doom-modeline-env-enable-go t)
(setq doom-modeline-env-enable-elixir t)
(setq doom-modeline-env-enable-rust t)

;; Change the executables to use for the language version string
(setq doom-modeline-env-python-executable "python") ; or `python-shell-interpreter'
(setq doom-modeline-env-ruby-executable "ruby")
(setq doom-modeline-env-perl-executable "perl")
(setq doom-modeline-env-go-executable "go")
(setq doom-modeline-env-elixir-executable "iex")
(setq doom-modeline-env-rust-executable "rustc")

;; What to dispaly as the version while a new one is being loaded
(setq doom-modeline-env-load-string "...")

;; Hooks that run before/after the modeline version string is updated
(setq doom-modeline-before-update-env-hook nil)
(setq doom-modeline-after-update-env-hook nil)
)
#+END_SRC
** Initialize =rainbow-mode=
*** Code
#+BEGIN_SRC emacs-lisp
(use-package rainbow-mode
  :straight t)
;; To enable in all programming-related modes (Emacs 24+):
(add-hook 'prog-mode-hook 'rainbow-delimiters-mode)
#+END_SRC
** Initialize =rainbow-delimeters=
*** Code
#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
  :straight t)
#+END_SRC
** Initialize =which-key=
*** Description
which-key is a minor mode for Emacs that displays the key bindings following your
currently entered incomplete command
*** Code
#+BEGIN_SRC emacs-lisp
(use-package which-key
  :straight t
  :config
  (which-key-mode))
#+END_SRC
** Initialize =fira-code-mode=
*** Description
This is a simple minor mode for Fira Code ligatures, built from [[https://github.com/tonsky/FiraCode/wiki/Emacs-instructions#using-prettify-symbols][these instructions on the FiraCode repo]].
*** code
#+BEGIN_SRC emacs-lisp
(use-package fira-code-mode
  :custom (fira-code-mode-disabled-ligatures '("[]" "#{" "#(" "#_" "#_(" "x")) ;; List of ligatures to turn off
  :hook prog-mode) ;; Enables fira-code-mode automatically for programming major modes
#+END_SRC
** Initialize =define-word=
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package define-word
    :straight t)
#+END_SRC
** Initialize =tex=
*** Description
 AUCTeX is an extensible package for writing and formatting
 TeX files in GNU Emacs.
*** Code
#+BEGIN_SRC emacs-lisp
         (use-package pdf-tools
          :magic ("%PDF" . pdf-view-mode)
          :config
          (pdf-tools-install)
          (setq-default pdf-view-display-size 'fit-page)
           ;; automatically annotate highlights
          (setq pdf-annot-activate-created-annotations t)
          ;; use normal isearch
          (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward)
          (define-key pdf-view-mode-map (kbd "C-r") 'isearch-backward))


        (defun try/TeX-command-save-buffer-and-run-all ()
        "Save the buffer and run TeX-command-run-all"
        (interactive)
        (let (TeX-save-query) (TeX-save-document (TeX-master-file)))
        (TeX-command-run-all nil))

        ;; copied ivy-bibtex and modified it to cite action
        (defun try/ivy-bibtex-cite (&optional arg local-bib)
          "Search BibTeX entries using ivy.

        With a prefix ARG the cache is invalidated and the bibliography
        reread.

        If LOCAL-BIB is non-nil, display that the BibTeX entries are read
        from the local bibliography.  This is set internally by
        `ivy-bibtex-with-local-bibliography'."
          (interactive "P")
          (when arg
        (bibtex-completion-clear-cache))
          (bibtex-completion-init)
          (let* ((candidates (bibtex-completion-candidates))
              (key (bibtex-completion-key-at-point))
              (preselect (and key
                      (cl-position-if (lambda (cand)
                            (member (cons "=key=" key)
                                (cdr cand)))
                              candidates))))
        (ivy-read (format "Insert citation %s: " (if local-bib " (local)" ""))
              candidates
              :preselect preselect
              :caller 'ivy-bibtex
              :history 'ivy-bibtex-history
              :action 'ivy-bibtex-insert-citation)))

        (defun try/latex-mode-setup ()
          (require 'company-reftex)
            (turn-on-reftex)
            (require 'company-auctex)
            (require 'company-math)
        (setq-local company-backends

        (append '(
                      (company-reftex-labels
                        company-reftex-citations)
              (company-math-symbols-unicode company-math-symbols-latex company-latex-commands)
              (company-auctex-macros company-auctex-symbols company-auctex-environments)
              company-ispell
              )
            company-backends)))


        (defun try/counsel-insert-file-path ()
          "Insert relative file path using counsel minibuffer"
          (interactive)
          (unless (featurep 'counsel) (require 'counsel))
          (ivy-read "Insert filename: " 'read-file-name-internal
            :matcher #'counsel--find-file-matcher
            :action
            (lambda (x)
              (insert (file-relative-name x)))))


        ;; Olivetti

        (use-package olivetti
          :diminish
          :hook (text-mode . olivetti-mode)
          :config
          (setq olivetti-body-width 100))



        ;; Enable folding and unfolding sections just like org-mode (using ~C-c-n~) using [[https://github.com/alphapapa/outshine/issues/85][outshine]]

        ;; Check ~outshine-cycle~ for more options.

        (use-package outshine
          :config
        (setq LaTeX-section-list '(
                       ("part" 0)
                       ("chapter" 1)
                       ("section" 2)
                       ("subsection" 3)
                       ("subsubsection" 4)
                       ("paragraph" 5)
                       ("subparagraph" 6)
                       ("begin" 7)
                       )
          )
        (add-hook 'LaTeX-mode-hook #'(lambda ()
                       (outshine-mode 1)
                       (setq outline-level #'LaTeX-outline-level)
                       (setq outline-regexp (LaTeX-outline-regexp t))
                       (setq outline-heading-alist
                         (mapcar (lambda (x)
                               (cons (concat "\\" (nth 0 x)) (nth 1 x)))
                             LaTeX-section-list))))

          )


  (add-hook 'LaTeX-mode-hook
        (lambda () (local-set-key (kbd "C-c n") '(outshine-cycle :which-key "outshine-cycle"))))

          ;; latexmk
          (use-package auctex-latexmk)
          ;; company
          (use-package company-math)
          (use-package company-auctex)
        (use-package company-reftex)


          ;;  use cdlatex
          (use-package cdlatex)

          ;; https://gist.github.com/saevarb/367d3266b3f302ecc896
          ;; https://piotr.is/2010/emacs-as-the-ultimate-latex-editor/

          (use-package latex
            :straight auctex
            :defer t
            :custom
            (olivetti-body-width 100)
            (cdlatex-simplify-sub-super-scripts nil)
            (reftex-default-bibliography
              '("~/ref.bib"))
            (bibtex-dialect 'biblatex)
            :mode
              ("\\.tex\\'" . latex-mode)
            :bind (:map LaTeX-mode-map
                  ("C-c C-e" . cdlatex-environment)
              )
            :hook
              (LaTeX-mode . olivetti-mode)
              (LaTeX-mode . TeX-PDF-mode)
              (LaTeX-mode . company-mode)
              (LaTeX-mode . flyspell-mode)
              (LaTeX-mode . flycheck-mode)
              (LaTeX-mode . LaTeX-math-mode)
              (LaTeX-mode . turn-on-reftex)
              (LaTeX-mode . TeX-source-correlate-mode)
              (LaTeX-mode . try/latex-mode-setup)
              (LaTeX-mode . turn-on-cdlatex)

            :config
              (setq TeX-auto-save t)
              (setq TeX-parse-self t)
              (setq-default TeX-master nil)
              (setq TeX-save-query nil)

              (setq reftex-plug-into-AUCTeX t)

              ;; pdftools
              ;; https://emacs.stackexchange.com/questions/21755/use-pdfview-as-default-auctex-pdf-viewer#21764
              (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
              TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
              TeX-source-correlate-start-server t) ;; not sure if last line is neccessary
              ;; to have the buffer refresh after compilation,
              ;; very important so that PDFView refesh itself after comilation
              (add-hook 'TeX-after-compilation-finished-functions
                  #'TeX-revert-document-buffer)

              ;; latexmk
              (require 'auctex-latexmk)
              (auctex-latexmk-setup)
              (setq auctex-latexmk-inherit-TeX-PDF-mode t))


      ;; ivy-bibtex
        (use-package ivy-bibtex
          :custom
          (bibtex-completion-bibliography
            '("~/ref.bib"))
          (bibtex-completion-library-path '("~/papers"))
          (bibtex-completion-cite-prompt-for-optional-arguments nil)
          (bibtex-completion-cite-default-as-initial-input t))

    ;; org-ref
          (use-package org-ref
        :custom
        (org-ref-default-bibliography "/tmp/ref.bib")
        (org-ref-pdf-directory "/tmp/papers")
        (org-ref-completion-library 'org-ref-ivy-cite)
        :config
        (require 'org-ref-wos)
        (require 'doi-utils))

  #+END_SRC
** Initialize =expand-region=
*** Description
Expand region increases the selected region by semantic units. Just keep pressing the key
until it selects what you want.
*** Code
#+BEGIN_SRC emacs-lisp
        (use-package expand-region
          :straight t
          :config
          (global-set-key (kbd "C-=") 'er/expand-region))
#+END_SRC
** Initialize =solaire-mode=
*** Description
solaire-mode is an aesthetic plugin designed to visually distinguish "real" buffers (i.e.
file-visiting code buffers where you do most of your work) from "unreal" buffers (like
popups, sidebars, log buffers, terminals, etc) by giving the latter a slightly different
-- often darker -- background
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package solaire-mode
    :ensure t)
#+END_SRC
** Built-in entry: =eldoc=
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package eldoc
    :straight nil
    :diminish eldoc-mode)
#+END_SRC
** Built-in entry: =abbrev=
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package abbrev
    :straight nil
    :diminish abbrev-mode)
#+END_SRC
* Programming
** Initialize =tree-sitter=
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package tree-sitter
    :straight t)
  (use-package tree-sitter-langs
    :straight t)
  (require 'tree-sitter)
    (require 'tree-sitter-langs)
#+END_SRC
** Initialize =elisp-bug-hunter=
*** Description
The Bug Hunter is an Emacs library that finds the source of an
error or unexpected behavior inside an elisp configuration file
(typically init.el or .emacs).
*** Code
#+BEGIN_SRC emacs-lisp
(use-package bug-hunter
  :straight t)
#+END_SRC

** Initialize =YASnippets=
*** Description
YASnippet is a template system for Emacs. It allows you to type an
abbreviation and automatically expand it into function templates
*** Code
#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :straight t
  :diminish yas
  :config
  (yas-global-mode 1)
)
;; Bundled snippets
(use-package yasnippet-snippets
  :straight t
  :config
  (yas-global-mode 1)
)
#+END_SRC
** Initialize =lua=
*** Code
#+BEGIN_SRC emacs-lisp
(use-package lua-mode
:straight t)
#+END_SRC
** Initialize =flychec=
*** Description
hecking extension for GNU Emacs, intended as replacement for the older Flymake extension which is part of GNU Emacs.
*** Code
#+BEGIN_SRC emacs-lisp
(use-package flycheck
 :straight t
 :init (global-flycheck-mode))
 (use-package flycheck-color-mode-line
  :straight t
  :config
  (eval-after-load "flycheck"
   '(add-hook 'flycheck-mode-hook 'flycheck-color-mode-line-mode)))
   (use-package pos-tip
    :straight t)
    (use-package flycheck-pos-tip
     :straight t
     :config
     (with-eval-after-load 'flycheck
  (flycheck-pos-tip-mode)))
#+END_SRC
** Initialize =company=
*** Description
Company is a text completion framework for Emacs.
The name stands for "complete anything".
*** Code
#+BEGIN_SRC emacs-lisp
(use-package company
 :straight t
 :config
 (global-company-mode))
#+END_SRC
** Initialize =lsp-mode=
*** Description
Client for Language Server Protocol (v3.14). lsp-mode aims to provide
IDE-like experience by providing optional integration with the most
popular Emacs packages like company, flycheck and projectile.
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package lsp-mode
    :straight t
    :init
    ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
    (setq lsp-keymap-prefix "C-l")
    :hook (c++-mode . lsp)
    :commands lsp)

  ;; optionally
  (use-package lsp-ui
   :straight t
   :init
   (setq lsp-ui-sideline-show-diagnostics nil)
   :commands lsp-ui-mode)
  ;; if you are ivy user
  (use-package lsp-ivy
   :straight t
   :commands lsp-ivy-workspace-symbol)
  (use-package lsp-treemacs
   :straight t
   :commands lsp-treemacs-errors-list)

  ;; optionally if you want to use debugger
  ;; (use-package dap-mode
  ;;  :straight t)
  ;; (use-package dap-LANGUAGE) to load the dap adapter for your language
#+END_SRC
** Initialize =racket-mode=
*** Code
#+BEGIN_SRC emacs-lisp
    (use-package racket-mode
      :straight t)
#+END_SRC
** Initialize =go-mode=
*** Code
#+BEGIN_SRC emacs-lisp
    (use-package go-mode
      :straight t)
#+END_SRC
** Initialize =php-mode=
*** Code
#+BEGIN_SRC emacs-lisp
    (use-package php-mode
      :straight t)
#+END_SRC
** Initialize =web-mode=
*** Description
web-mode.el is an emacs major mode for editing web templates aka HTML
files embedding parts (CSS/JavaScript) and blocks (pre rendered by
client/server side engines).
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package web-mode
      :straight t)
#+END_SRC
** Initialize =rust-mode=
*** Code
#+BEGIN_SRC emacs-lisp
    (use-package rust-mode
      :straight t)
#+END_SRC
** Initialize =json-mode=
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package json-mode
    :straight t)
#+END_SRC
** Initialize =Indium=
*** Description
A JavaScript development environment for Emacs.
*** Code
#+BEGIN_SRC emacs-lisp
  (use-package indium
    :straight t)
#+END_SRC
