#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i

bspc config top_padding 14
bspc config focus_follow_pointer true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Setting the wallpaper
feh --bg-scale ~/.config/wall.png &

# Lovely transitions and transparency with compton
compton --config ~/.config/compton/compton.conf -f &

# Polybar
~/scripts/Launch_Polybar.sh &

# Starting Pulseaudio becaue it doesn't start automatically for some reason
pulseaudio --start &

# Start Dunst
~/scripts/Launch_Dunst.sh &

redshift -c /home/anthony/.config/redshift.conf &

kdeconnect-indicator &

nextcloud &

nm-applet &

sxhkd -c ~/.config/sxhkd/sxhkdrc &

# xsetroot -cursor_name left_ptr &

xrdb -merge ~/.Xresources

dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
